from typing import Any

class Logger:
    def remove(self, handler_id: int | None = ...) -> None: ...
    def add(self, sink: Any, *, level: str | int = ..., colorize: bool = ..., backtrace: bool = ..., diagnose: bool = ..., format: str = ...) -> int: ...
    def info(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> None: ...

logger: Logger
